update main.yml for github actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -54,9 +54,7 @@ jobs:
   build-and-ui-testing:
     runs-on: ubuntu-latest
     concurrency: ci-${{ github.ref }}
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
+    environment: github-pages
     strategy:
       matrix:
         node-version: [20.x]
@@ -74,6 +72,8 @@ jobs:
         if: always()
       - run: npm run test:ui:report
         if: always()
+      - name: Debug .loki
+        run: ls -la .loki || echo ".loki not found"
       - name: Check .loki exists
         run: |
           if [ ! -d ".loki" ]; then
@@ -88,7 +88,7 @@ jobs:
         if: always()
         with:
           path: ".loki"
-          name: github-pages 
+          name: github-pages
       - name: Deploy to GitHub Pages
         id: deployment
         if: always()
