update main.yml for github actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,24 +62,24 @@ jobs:
         node-version: [20.x]
     steps:
       - uses: actions/checkout@v4
-      - name: Staring Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v3
+      - uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-      - name: install modules
-        run: npm ci --force
-      - name: build production project
-        run: npm run build:prod
+      - run: npm ci --force
+      - run: npm run build:prod
         if: always()
-      - name: build storybook
-        run: npm run storybook:build
+      - run: npm run storybook:build
         if: always()
-      - name: screenshot testing
-        run: npm run test:ui:ci
+      - run: npm run test:ui:ci
         if: always()
-      - name: Generate HTML report
-        run: npm run test:ui:report
+      - run: npm run test:ui:report
         if: always()
+      - name: Check .loki exists
+        run: |
+          if [ ! -d ".loki" ]; then
+            echo ".loki folder not found!"
+            exit 1
+          fi
       - name: Setup Pages
         uses: actions/configure-pages@v2
         if: always()
@@ -88,6 +88,7 @@ jobs:
         if: always()
         with:
           path: ".loki"
+          name: github-pages 
       - name: Deploy to GitHub Pages
         id: deployment
         if: always()
